const baseValues = {
  runeRenderingColourSaturation: 100,
  runeRenderingThickness: 15,
};

export const RUNE_ANIMATIONS_GROWING_DURATION = 250;
export const RUNE_ANIMATIONS_GROWING_FROM_OPACITY = 0.7;
export const RUNE_ANIMATIONS_GROWING_RADIUS = baseValues.runeRenderingThickness;
export const RUNE_ANIMATIONS_GROWING_TO_OPACITY = 0;
export const RUNE_ANIMATIONS_GROWING_TO_RADIUS_MULTIPLIER = 3;
export const RUNE_ANIMATIONS_RUNNING_LEAVE_X_VERTICES = 1;
export const RUNE_ANIMATIONS_RUNNING_REMOVE_ONE_VERTEX_EVERY_X_MILLISECONDS = 8;
export const RUNE_ANIMATIONS_WITHERING_DURATION = 250;
export const RUNE_ANIMATIONS_WITHERING_FROM_SATURATION = baseValues.runeRenderingColourSaturation;
export const RUNE_ANIMATIONS_WITHERING_FROM_THICKNESS = baseValues.runeRenderingThickness;
export const RUNE_ANIMATIONS_WITHERING_TO_SATURATION = 0;
export const RUNE_ANIMATIONS_WITHERING_TO_THICKNESS = 0;
export const RUNE_DIMENSIONS_HEIGHT = 500;
export const RUNE_DIMENSIONS_LEFT = 0;
export const RUNE_DIMENSIONS_TOP = 0;
export const RUNE_DIMENSIONS_WIDTH = 320;
export const RUNE_LAZY_RADIUS = 5;
export const RUNE_MAX_TIME_OUT_OF_BOUNDS = 500;
export const RUNE_MINIMAL_VIABLE_LENGTH = 15;
export const RUNE_RENDERING_COLOUR_ALPHA = 0.7;
export const RUNE_RENDERING_COLOUR_HUE = 40;
export const RUNE_RENDERING_COLOUR_LIGHTNESS = 50;
export const RUNE_RENDERING_COLOUR_SATURATION = baseValues.runeRenderingColourSaturation;
export const RUNE_RENDERING_SHADOW_BLUR = 10;
export const RUNE_RENDERING_SHADOW_COLOUR_ALPHA = 0.4;
export const RUNE_RENDERING_SHADOW_COLOUR_HUE = 40;
export const RUNE_RENDERING_SHADOW_COLOUR_LIGHTNESS = 50;
export const RUNE_RENDERING_SHADOW_COLOUR_SATURATION = 100;
export const RUNE_RENDERING_THICKNESS = baseValues.runeRenderingThickness;
