import {
  COUNTER_RUNE_RENDERING_COLOUR_ALPHA,
  COUNTER_RUNE_RENDERING_COLOUR_HUE,
  COUNTER_RUNE_RENDERING_COLOUR_LIGHTNESS,
  COUNTER_RUNE_RENDERING_COLOUR_SATURATION,
  COUNTER_RUNE_RENDERING_SHADOW_BLUR,
  COUNTER_RUNE_RENDERING_SHADOW_COLOUR_ALPHA,
  COUNTER_RUNE_RENDERING_SHADOW_COLOUR_HUE,
  COUNTER_RUNE_RENDERING_SHADOW_COLOUR_LIGHTNESS,
  COUNTER_RUNE_RENDERING_SHADOW_COLOUR_SATURATION,
  COUNTER_RUNE_RENDERING_THICKNESS,
} from "../../config/values.js";
import { HSLA } from "../../HSLA";

export const makeRendering = () => ({
  colour: new HSLA({
    h: COUNTER_RUNE_RENDERING_COLOUR_HUE,
    s: COUNTER_RUNE_RENDERING_COLOUR_SATURATION,
    l: COUNTER_RUNE_RENDERING_COLOUR_LIGHTNESS,
    a: COUNTER_RUNE_RENDERING_COLOUR_ALPHA,
  }),
  radius: COUNTER_RUNE_RENDERING_THICKNESS,
  shadowColour: new HSLA({
    h: COUNTER_RUNE_RENDERING_SHADOW_COLOUR_HUE,
    s: COUNTER_RUNE_RENDERING_SHADOW_COLOUR_SATURATION,
    l: COUNTER_RUNE_RENDERING_SHADOW_COLOUR_LIGHTNESS,
    a: COUNTER_RUNE_RENDERING_SHADOW_COLOUR_ALPHA,
  }),
  shadowBlur: COUNTER_RUNE_RENDERING_SHADOW_BLUR,
  thickness: COUNTER_RUNE_RENDERING_THICKNESS,
  vertices: [],
});
