import { HSLA } from "../../../HSLA";
import {
  RUNE_RENDERING_COLOUR_ALPHA,
  RUNE_RENDERING_COLOUR_HUE,
  RUNE_RENDERING_COLOUR_LIGHTNESS,
  RUNE_RENDERING_COLOUR_SATURATION,
  RUNE_RENDERING_SHADOW_BLUR,
  RUNE_RENDERING_SHADOW_COLOUR_ALPHA,
  RUNE_RENDERING_SHADOW_COLOUR_HUE,
  RUNE_RENDERING_SHADOW_COLOUR_LIGHTNESS,
  RUNE_RENDERING_SHADOW_COLOUR_SATURATION,
  RUNE_RENDERING_THICKNESS,
} from "../../../values.js";

export const makeRendering = () => ({
  colour: new HSLA({
    h: RUNE_RENDERING_COLOUR_HUE,
    s: RUNE_RENDERING_COLOUR_SATURATION,
    l: RUNE_RENDERING_COLOUR_LIGHTNESS,
    a: RUNE_RENDERING_COLOUR_ALPHA,
  }),
  radius: RUNE_RENDERING_THICKNESS,
  shadowColour: new HSLA({
    h: RUNE_RENDERING_SHADOW_COLOUR_HUE,
    s: RUNE_RENDERING_SHADOW_COLOUR_SATURATION,
    l: RUNE_RENDERING_SHADOW_COLOUR_LIGHTNESS,
    a: RUNE_RENDERING_SHADOW_COLOUR_ALPHA,
  }),
  shadowBlur: RUNE_RENDERING_SHADOW_BLUR,
  thickness: RUNE_RENDERING_THICKNESS,
  vertices: [],
});
